-- MySQL Script generated by MySQL Workbench
-- Κυρ 05 Ιούν 2016 12:44:23 μμ EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tedDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tedDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tedDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `tedDB` ;

-- -----------------------------------------------------
-- Table `tedDB`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tedDB`.`Location` (
  `idLocation` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `postal_code` INT NULL,
  `latitude` FLOAT NULL,
  `longitude` FLOAT NULL,
  `location` VARCHAR(45) NULL,
  PRIMARY KEY (`idLocation`),
  UNIQUE INDEX `idLocation_UNIQUE` (`idLocation` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tedDB`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tedDB`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `afm` VARCHAR(45) NOT NULL,
  `rating_bidder` FLOAT NULL,
  `rating_seller` FLOAT NULL,
  `admin` TINYINT(1) NOT NULL,
  `verified` TINYINT(1) NOT NULL,
  `idLocation` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  INDEX `fk_User_Location1_idx` (`idLocation` ASC),
  CONSTRAINT `fk_User_Location1`
    FOREIGN KEY (`idLocation`)
    REFERENCES `tedDB`.`Location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tedDB`.`Bid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tedDB`.`Bid` (
  `idBid` INT NOT NULL AUTO_INCREMENT,
  `idItem` INT NOT NULL,
  `idBidder` INT NOT NULL,
  `amount` FLOAT NOT NULL,
  `time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idBid`),
  INDEX `fk_Bid_Item_idx` (`idItem` ASC),
  INDEX `fk_Bid_User1_idx` (`idBidder` ASC),
  UNIQUE INDEX `idBid_UNIQUE` (`idBid` ASC),
  CONSTRAINT `fk_Bid_Item`
    FOREIGN KEY (`idItem`)
    REFERENCES `tedDB`.`Item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bid_User1`
    FOREIGN KEY (`idBidder`)
    REFERENCES `tedDB`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tedDB`.`Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tedDB`.`Image` (
  `idImage` INT NOT NULL AUTO_INCREMENT,
  `image` BLOB NOT NULL,
  PRIMARY KEY (`idImage`),
  UNIQUE INDEX `idImage_UNIQUE` (`idImage` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tedDB`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tedDB`.`Item` (
  `idItem` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `buy_price` VARCHAR(45) NOT NULL,
  `first_bid` VARCHAR(45) NOT NULL,
  `number_of_bids` INT NOT NULL,
  `currently` INT NOT NULL,
  `idLocation` INT NOT NULL,
  `started` TIMESTAMP NULL,
  `ends` TIMESTAMP NULL,
  `description` LONGTEXT NOT NULL,
  `idImage` INT NULL,
  `idSeller` INT NOT NULL,
  PRIMARY KEY (`idItem`),
  UNIQUE INDEX `idItem_UNIQUE` (`idItem` ASC),
  INDEX `fk_Item_Bid1_idx` (`currently` ASC),
  INDEX `fk_Item_Location1_idx` (`idLocation` ASC),
  INDEX `fk_Item_Image1_idx` (`idImage` ASC),
  INDEX `fk_Item_User1_idx` (`idSeller` ASC),
  CONSTRAINT `fk_Item_Bid1`
    FOREIGN KEY (`currently`)
    REFERENCES `tedDB`.`Bid` (`idBid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_Location1`
    FOREIGN KEY (`idLocation`)
    REFERENCES `tedDB`.`Location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_Image1`
    FOREIGN KEY (`idImage`)
    REFERENCES `tedDB`.`Image` (`idImage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_User1`
    FOREIGN KEY (`idSeller`)
    REFERENCES `tedDB`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tedDB`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tedDB`.`Category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategory`),
  UNIQUE INDEX `idCategory_UNIQUE` (`idCategory` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tedDB`.`ItemCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tedDB`.`ItemCategory` (
  `idItem` INT NOT NULL,
  `idCategory` INT NOT NULL,
  PRIMARY KEY (`idItem`, `idCategory`),
  INDEX `fk_Item_has_Category_Category1_idx` (`idCategory` ASC),
  INDEX `fk_Item_has_Category_Item1_idx` (`idItem` ASC),
  CONSTRAINT `fk_Item_has_Category_Item1`
    FOREIGN KEY (`idItem`)
    REFERENCES `tedDB`.`Item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_has_Category_Category1`
    FOREIGN KEY (`idCategory`)
    REFERENCES `tedDB`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tedDB`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tedDB`.`Message` (
  `idMessage` INT NOT NULL AUTO_INCREMENT,
  `idSender` INT NOT NULL,
  `idReceiver` INT NOT NULL,
  `message` LONGTEXT NULL,
  `read` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idMessage`),
  INDEX `fk_User_has_User_User2_idx` (`idReceiver` ASC),
  INDEX `fk_User_has_User_User1_idx` (`idSender` ASC),
  UNIQUE INDEX `idMessage_UNIQUE` (`idMessage` ASC),
  CONSTRAINT `fk_User_has_User_User1`
    FOREIGN KEY (`idSender`)
    REFERENCES `tedDB`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_User_User2`
    FOREIGN KEY (`idReceiver`)
    REFERENCES `tedDB`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tedDB`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tedDB`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `afm` VARCHAR(45) NOT NULL,
  `rating_bidder` FLOAT NULL,
  `rating_seller` FLOAT NULL,
  `admin` TINYINT(1) NOT NULL,
  `verified` TINYINT(1) NOT NULL,
  `idLocation` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  INDEX `fk_User_Location1_idx` (`idLocation` ASC),
  CONSTRAINT `fk_User_Location1`
    FOREIGN KEY (`idLocation`)
    REFERENCES `tedDB`.`Location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
